name: Build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    paths-ignore:
      - "**/**.md"

jobs:
  build:
    strategy:
      matrix:
        build_system:
          - cmake
          - meson
          - autoconf
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libjansson-dev meson
      - name: Checkout libjwt
        uses: actions/checkout@v4
        with:
          repository: "benmcollins/libjwt"
          ref: "v1.17.0"
          path: "libjwt"
      - name: Configure libjwt
        run: |
          install -d libjwt-build
          cmake -B libjwt-build -S libjwt -DBUILD_SHARED_LIBS=ON
      - name: Build libjwt
        run: |
          cmake --build libjwt-build
      - name: Install libjwt
        run: |
          sudo cmake --install libjwt-build --prefix /usr
      - name: Checkout mod_authn_jwt
        uses: actions/checkout@v4
        with:
          path: "mod_authn_jwt"
      - name: Checkout lighttpd
        uses: actions/checkout@v4
        with:
          repository: "lighttpd/lighttpd1.4"
          ref: "lighttpd-1.4.75"
          path: "lighttpd"
      - name: Patch lighttpd
        run: |
          cp mod_authn_jwt/mod_authn_jwt.c lighttpd/src
          cp mod_authn_jwt/*.patch lighttpd
          cd lighttpd
          patch -p1 <CMakeLists.txt.patch
          patch -p1 <meson.patch
          patch -p1 <autoconf.patch
      - if: matrix.build_system == 'cmake'
        name: Configure with CMake
        run: |
          install -d build
          cmake -B build -S lighttpd -DWITH_JWT=ON
      - if: matrix.build_system == 'cmake'
        name: Build with CMake
        run: |
          cmake --build build
      - if: matrix.build_system == 'cmake'
        name: Test with CMake
        run: |
          ctest --test-dir build
      - if: matrix.build_system == 'meson'
        name: Configure with Meson
        run: |
          meson setup -Dwith_jwt=enabled build lighttpd
      - if: matrix.build_system == 'meson'
        name: Build with Ninja
        run: |
          cd build
          ninja
      - if: matrix.build_system == 'meson'
        name: Test with Meson
        run: |
          cd build
          meson test
      - if: matrix.build_system == 'autoconf'
        name: Configure
        run: |
          cd lighttpd
          ./autogen.sh
          ./configure --with-jwt
      - if: matrix.build_system == 'autoconf'
        name: Build
        run: |
          cd lighttpd
          make
      - if: matrix.build_system == 'autoconf'
        name: Test
        run: |
          cd lighttpd
          make check
